# Generated by Django 5.1.3 on 2024-11-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='플레이리스트 제목')),
                ('link', models.URLField(max_length=256, verbose_name='플레이리스트 주소')),
                ('cover_image', models.URLField(max_length=256, verbose_name='커버 이미지 링크')),
            ],
            options={
                'verbose_name': '스포티파이 플레이리스트',
                'verbose_name_plural': '스포티파이 플레이리스트 목록',
                'db_table': 'spotify_playlist',
            },
        ),
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_music', models.CharField(max_length=256, verbose_name='추천된 노래 제목')),
                ('playlist_title', models.CharField(max_length=256, verbose_name='플레이리스트 제목')),
                ('playlist_url', models.URLField(max_length=256, verbose_name='플레이리스트 URL')),
            ],
            options={
                'verbose_name': '유튜브 플레이리스트',
                'verbose_name_plural': '유튜브 플레이리스트 목록',
                'db_table': 'youtube_playlist',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_music', models.CharField(max_length=256, verbose_name='추천된 노래 제목')),
                ('video_title', models.CharField(max_length=256, verbose_name='동영상 제목')),
                ('video_url', models.URLField(max_length=256, verbose_name='동영상 URL')),
            ],
            options={
                'verbose_name': '유튜브 동영상',
                'verbose_name_plural': '유튜브 동영상 목록',
                'db_table': 'youtube_video',
            },
        ),
    ]
